config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "items#index"
  resources :items, only: [:index, :new, :create]
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord


validates :brand_name, presence: true
validates :product_name, presence: true
validates :category_id, presence: true
validates :price, presence: true

belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'Include both letters and numbers'
  validates_format_of :password, with: PASSWORD_REGEX, message: 'is invalid'
  validates :nick_name, presence: true
  validates :age, presence: true

  has_many :item

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nick_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:age])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end
  

  private

  def item_params
    params.require(:item).permit(:brand_name, :product_name, :category_id, :price).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<%= form_with model: @item, local: true do |f|%>
  <div class="field">
    <%= f.label :brand_name, "ブランドの名前" %><br />
    <%= f.text_field :brand_name, id:"prototype_title" %>
  </div>

  <div class="field">
    <%= f.label :product_name, "商品の名前" %><br />
    <%= f.text_field :product_name,  id:"prototype_catch_copy" %>
  </div>

  <div class="field">
    <%= f.label :category_id, "商品のカテゴリー" %><br />
    <%= f.text_field :category_id,  id:"prototype_concept" %>
  </div>

  <div class="field">
    <%= f.label :price, "価格（税込）" %><br />
    <%= f.text_field :price, id:"prototype_image" %>
  </div>

  <div class="actions">
    <%= f.submit " 投稿する", class: :form__btn  %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div class="card">
  <%= link_to "ブランドの名前", root_path, class: :card__title%>
  <div class="card__body">
    <%= link_to "商品の名前", root_path, class: :card__title%>
    <div class="card__body">
    <%= link_to "商品のカテゴリー", root_path, class: :card__title%>
    <div class="card__body">
    <div class="card__body">
    <%= link_to "価格", root_path, class: :card__title%>
    <div class="card__body">
    <%= link_to "by 投稿者名", root_path, class: :card__user %>
  </div>
</div>

app/views/items/index.html.erb
<main class="main">
  <div class="inner">
     <% if user_signed_in? %>
      <div class="greeting"> 
        <%= "こんにちは、" %>
         <%= link_to "#{current_user.nick_name}さん ", user_path(id: current_user.id), class: :greeting__link%>
       </div> 
       <% end %>
    <div class="card__wrapper">
     <%= render partial: 'item', collection: @items %>
    </div>
  </div>
</main>

app/views/items/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規アイテム投稿</h2>
        <%= render 'items/form' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BAG-APP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("Bag-app.png", class: :logo), root_path %>
          </div>
             <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "New Item", new_item_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
            <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html>